### ISSUE TITLE
Update or new single objective plot for multi-objective optimizations 

### ISSUE THREAD

**Issue by DanSava** [equinor/everviz#79] opened 2020-05-12 14:29 UTC
In the case of a multiple objective optimization, either add a new plot or change the objective plot to include all objective functions with their respective weights, and/or plot N weighted objective functions. In order to see the contribution of each of the objectives have on the resulting single objective function.

**Comment by markusdregi** [comment] 2020-05-20 08:02
Ensure that weighted and scaled objective function values are available for visualisation.

**Comment by markusdregi** [comment] 2020-05-20 08:05
Duplicate of #87

**Closed by markusdregi** 2020-05-20 08:05 UTC
