### ISSUE TITLE
Summary values

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#115] opened 2020-06-25 13:38 UTC
When changing from statistics to values the axis resets to 1970 with no values, possibly because there are nan`s in the data set?

**Comment by DanSava** [comment] 2020-06-30 09:26
I could not reproduce this issue

If possible check if this issue is still persisting after the fix merged in #122

**Comment by oyvindeide** [comment] 2020-06-30 12:20
I think that would fix the problem, at least that is what I suspected would be the issue. I will confirm and close if fixed.

**Comment by oyvindeide** [comment] 2020-06-30 12:59
Can still replicate the problem on my test case, now I get a: `KeyError: 1969-12-31 23:59:59`  can point you to my test case if you'd like?

**Comment by oyvindeide** [comment] 2020-06-30 14:08
So this can be fixed in a number of ways, the main question is, should this be considered a bug of the `everest` api? In the case of `summary_keys` I would argue that it might be. It is now passing along a bunch of time steps that are invalid. `everest` has the context to filter it out, `everviz`  technically does not. There are ways around that, but they are a bit hacky.

**Comment by DanSava** [comment] 2020-06-30 14:11
If Everest is passing along timesteps that are invalid then I would say it is a bug in the Everest data API, and it should be fixed there.

**Closed** 2020-07-06 08:25 UTC
